apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: postgres-label
spec:
  ports:
    - port : 5432
      targetPort: 5432
  selector:
    app: postgres-pod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre-dep
spec:
  selector:
    matchLabels:
      app: postgres-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-pod
    spec:
      containers:
      - name: postgre-container
        image: quay.io/redhatdemo/openshift-pgsql12-primary:centos7
        imagePullPolicy: Always
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres