apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-label
spec:
  ports:
    - port : 6379
      targetPort: 6379
  selector:
    app: redis-pod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-dep
spec:
  selector:
    matchLabels:
      app: redis-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-pod
    spec:
      containers:
      - name: redis-container
        image: redis
        ports:
        - containerPort: 6379