apiVersion: v1
kind: Service
metadata:
  name: result
  labels:
    name: result-label
spec:
  type: NodePort
  ports:
    - port : 80
      targetPort: 8010
      nodePort: 30004
  selector:
     app: result-app-pod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  result-app-depl-name
  labels:
    app: result-app-depl-label
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result-app-pod
  template:
    metadata:
      labels:
        app: result-app-pod
    spec:
      containers:
        - name: voting-app-container
          image: dockersamples/examplevotingapp_result
          ports:
            - containerPort: 80