apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app-deploy-net
  labels:
    app: net
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-app-pod
  template:
    metadata:
      labels:
        app: worker-app-pod
    spec:
      containers:
        - name: worker-app-container
          image: dockersamples/examplevotingapp_worker
          